version: '3.8'
services:
  hbbs:
    image: rustdesk/rustdesk-server
    container_name: hbbs
    command: hbbs
    ports:
      - "21115-21119:21115-21119"
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server
    container_name: hbbr
    command: hbbr
    ports:
      - "21117:21117"
      - "21119:21119"
    restart: unless-stopped
